name: easy_translator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  easy_localization: ^3.0.7+1
  http: ^1.3.0
  yaml: ^3.1.3
  yaml_edit: ^2.2.2
# path: ^1.8.0
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
